spring.application.name=eungda

# 1. Oracle DB 접속 정보
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=c##yui
spring.datasource.password=1234

# 2. JPA & Hibernate 설정
# update: 서버가 켜질 때 Entity를 분석해서 DB에 없는 테이블을 자동으로 만들어줌
spring.jpa.hibernate.ddl-auto=update
# DB로 날아가는 실제 쿼리를 콘솔에 예쁘게 보여줌
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true